### PR TITLE
Unittest

### PR DESCRIPTION
**Pull request by reillymck**
Beginning framework for unittests. Currently runs a test for compare_v.import_design(), and compare_v_refactor.import_design. Test is not comprehensive and does not currently check for accuracy, but checks that import_design produces the same result as corey's code + the bug fixes in my other PR.

### CODE REVIEW

**Review by dallinjdahl — CHANGES_REQUESTED** [review]
I think we should change the name of the file to reflect the class, something like `compare_v_test.py`?

Also, I don't know how I feel about testing against a previous commit, what if we accidentally commit bad data?  I would prefer to have a simple design and test it explicitly, checking in the test for things we know exist.  That could be a committed design I guess, but we want to make sure it's not subject to change.  The only thing changing should be the import code, not the test (within reason).

**Comment by reillymck** [comment]
I have a committed design in test_reaources (aes128). I plan on adding a simpler design as well. I intended for the tests.py to cover all files, but we can do a separate test file for each one for sure. I wrote tests to make sure the refactor functions matched what Corey had (minus bugs). I do think I can add some functionality tests.

**Comment by reillymck** [comment]
I didn't intend for the previous commit to change (unless there was a bug fix) but the previous commit to be Corey's code as baseline.

**Comment by dallinjdahl** [comment]
Got it.  I was more thinking that if we tested to make sure the code works, then it doesn't really matter if it matches Corey's.  Granted, it's often hard to know if it works :)

**Comment by reillymck** [comment]
I agree for functionality, Corey's can just be a start to make sure we aren't doing worse. Over the next couple weeks I'll put in some functionality tests.

**Pull request merged**
